name: 'Business Greetings'
description: 'Offers professional greetings and timestamps them'


inputs:
  name:
    description: 'Name of the person or team to greet'
    required: true
    default: 'Ah Liang'
outputs:
  timestamp:
    description: 'Time of greeting'
runs:
  using: 'node20'
  main: 'index.js'